{{- define "ioc-chart.deployment" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Chart.AppVersion | quote }}
    is_ioc: "True"
  annotations:
    kubernetes.io/change-cause: {{ .Chart.AppVersion }} deployed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        beamline: {{ .Values.beamline }}
        ioc_version: {{ .Chart.AppVersion | quote }}
        is_ioc: "True"
    spec:
      serviceAccountName: {{ .Values.serviceAccount | default "epics-iocs-priv" | quote }}
      hostNetwork: {{ .Values.hostNetwork }}
      terminationGracePeriodSeconds: 5 # nice to have quick restarts on IOCs
      volumes:
        {{if .Values.autosave }}
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
        {{- end }}
        {{- if .Values.dataVolume }}
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-data
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          allowPrivilegeEscalation: false
        image: {{ .Values.base_image }}
        command:
          - bash
        args:
          - {{ .Values.iocFolder }}/config/start.sh
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.iocFolder }}/config
        {{if .Values.autosave }}
        - name: {{ .Chart.Name }}
          mountPath: /autosave
        {{- end }}
        {{- if .Values.dataVolume }}
        - name: {{ .Chart.Name }}-data
          mountPath: /data
        {{- end }}
        stdin: true
        tty: true
        resources: {{ .Values.resources }}
        imagePullPolicy: Always
        env:
        - name: IOCSH_PS1
          value: "{{ .Chart.Name }} > "
        - name: IOC_NAME
          value: {{ .Chart.Name }}
        - name: IOC_VERSION
          value: {{ .Chart.AppVersion | quote }}
      {{- if .Values.useAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - {{ .Values.beamline }}
      {{- end }}
      tolerations:
        - key: nodetype
          operator: Equal
          value: {{ .Values.beamline }}
          effect: NoSchedule


{{ end }}