apiVersion: v2
name: helm-ioc-lib
description: A Helm Chart Library for all IOC instances

type: library

# These versions will be updated by CI to match the git tag
version: "1.0.0"
appVersion: "1.0.0"
