apiVersion: v2
name: bl45p-mo-ioc-01
description: |
  main motion IOC for the bl45p test beamline

type: application

# chart and app version - these are updated automatically by CI
version: 2021.2.0
appVersion: 2021.2.0

dependencies:
  - name: bl45p-chart
    version: "1.0.0"
    repository: file://../../bl45p-chart
    import-values:
      - beamline_defaults
  - name: helm-ioc-lib
    version: "1.0.0"
    repository: file:///scratch/hgv27681/work/epics-containers/helm-ioc-lib
    import-values:
      - defaults
