
{{ include "ioc-chart.ioc" . }}

{{- /*
  add the contents of every file in the config folder of this IOC helm chart
  into the config map - this must include start.sh the startup script.
  The files must be text only. Any files ending in .tz are explicitly omitted
*/ -}}

{{ (.Files.Glob "config/*").AsConfig | indent 2 }}

  version.txt: |
    IOC {{ .Release.Name }} version {{ .Chart.AppVersion }}